### ISSUE TITLE
Support for setting different cranelift flags / wasmtime::Config flags

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/sightglass#103]
It would be nice to benchmark these configurations (both one off and continuously over time):

* builds w/ vs w/out debug info
* optimized(speed) vs optimized(speed + size) vs not optimized
* bounds checking strategy (explicit vs virtual memory)
* with or without fuel

All of these things require dynamically setting flags on cranelift and/or wasmtime.

**Comment by cfallin** [comment]
A proposal: we could extend the syntax for engine specifications (`wasmtime@branch@https://repo/path`) to include settings as well, taking inspiration from URLs' query strings. Perhaps something like:

`wasmtime@branch@https://github.com/my_fork_of/wasmtime?regalloc=linearscan&fuel=true&heapchecks=explicit`

We can bikeshed on the syntax -- no need to literally use the query-string format -- but it seems like having a single string that uniquely identifies (i) engine, (ii) which exact revision/source tree of that engine to use, and (iii) runtime configuration of that engine, would be very useful.

**Comment by abrown** [comment]
@cfallin, I have a solution for the above on a branch in my private repository: [`BuildInfo`](https://github.com/abrown/sightglass/blob/fingerprint/crates/build/src/buildinfo.rs). It is a mechanism for both specifying the configuration of an engine when we built it and a way to capture that configuration to allow a reproducible build. I've found it helpful for uploading Sightglass data to the ES/Kibana server I'm using.

But before we can switch to that, we need a way to pass the runtime flags of the engine: I propose we do so as an opaque string and, on the Wasmtime bench API side, parse that string using the current CLI structopt parsing (this way there is no confusion when running benchmarks). So let me re-phrase what the problems are with this proposal, adapted from https://github.com/bytecodealliance/sightglass/pull/164#issuecomment-1097107532: in looking into this, we could use the structopt-enabled [`CommonOptions`](https://github.com/bytecodealliance/wasmtime/blob/main/src/lib.rs#L142) to transform a string into a [`Config`](https://github.com/bytecodealliance/wasmtime/blob/main/crates/wasmtime/src/config.rs#L83) by using the structopt `from_iter` function. The issue is that `CommonOptions` is private in the `wasmtime-cli` crate and `Config` lives in the `wasmtime` crate.

How could we use the same parsing as the `wasmtime-cli` crate, but in the `wasmtime-bench-api` crate? 
  a. make `CommonOptions` public so that `wasmtime-bench-api` can rely on it,
  b. make `Config` parse-able from a string (perhaps by moving `CommonOptions` somewhere closer but bringing in a structopt dependency)
  c. move the parsing logic to some third location that can be depended on by `wasmtime-cli` and `wasmtime-bench-api`

@cfallin, @alexcrichton, any thoughts on the best option here?

**Comment by alexcrichton** [comment]
Personally I'm not certain it's worth going out of our way to avoid code duplication here. The needs of the CLI and a string configuration system like this seem fairly different so it's not clear to me that we could easily use one for the other. I think it'd be fine to define custom syntax for the wasmtime-bench-api crate just used there.

**Comment by abrown** [comment]
This should now be possible due to https://github.com/bytecodealliance/sightglass/pull/175, https://github.com/bytecodealliance/wasmtime/pull/4096, and https://github.com/bytecodealliance/wasmtime/pull/4207. It would look something like:

```
sightglass-cli benchmark --engine-flags "--cranelift-enable ..." ...
```
