### ISSUE TITLE
sightglass-next: measure everything by default

### ISSUE THREAD

**Issue by fitzgen** [bytecodealliance/sightglass#79]
We can measure multiple perf counters and also wall time at the same time, no need to run the benchmarks multiple times, once for each measurement (which balloons experiment time).

**Comment by abrown** [comment]
The perf counters have a `cpu-cycles` event... but it is likely adjusted.

**Comment by abrown** [comment]
I've thought more about this issue since it was opened: I considered adding some kind of "and" functionality for using multiple measures at the same time but in the end didn't implement it because I was concerned that it would be tricky to measure both with `RDTSC` and `perf` without interfering. I.e., `perf_event_open` is some non-negligible work that we would not want to measure so we would have to place the `RDTSC` calls on the inner side of those (closest to the actual work); this is possible but would require careful documentation (or something) to prevent future re-factorings from introducing interference. It seemed simpler to just avoid this problem altogether, especially if we consider a third measurement (e.g., where would VTune insert its hooks without interfering with `RDTSC` or `perf`?).

Since the `perf` counters already have a similar cycle-based event (though measured slightly differently), perhaps we could resolve this by just making `perf` the default measure on Linux? @fitzgen, what do you think?

**Comment by fitzgen** [comment]
That sounds good to me

**Comment by abrown** [comment]
After discussing this more, I think it makes sense to keep the current default `cycles`, since having different default behavior on different systems could be confusing. It would be great if we could find a reliable `insts-retired` measure for Mac and Windows and then that is probably a less noisy default. For users who want more data than just `cycles`, check out the `perf-counters` or `vtune` measures, both of which will provide access to more information.
