### ISSUE TITLE
sightglass-next: modify lucet to use new runner

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/sightglass#92]
The two known users of the original Sightglass code (see [`src`](src)) are:
 - lucet, see the Git submodule and the [`benchmarks`](https://github.com/bytecodealliance/lucet/tree/main/benchmarks) directory
 - webui_runner, a component of Sightglass (see [`webui_runner`](webui_runner))

If lucet migrates to sightglass-next, then it is significantly easier to refactor this repository to remove the old Sightglass code.

**Comment by abrown** [comment]
@fitzgen, we didn't talk about this, but can you take a look at this? Or someone else at Fastly?

**Comment by fitzgen** [comment]
@iximeow told me that those benchmarks / that usage can simply be removed from Lucet at this point in time. So whenever we're ready to flip the switch here, we can give Lucet folks the heads up so they can remove that stuff first, rather than get surprised with broken CI, and then we can make the new runner the default.

**Comment by abrown** [comment]
Lucet is now an archived project, closing.
